# Generated by Django 2.1.1 on 2018-10-12 00:01

from django.db import migrations
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181003_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(upload_to='picture/news'),
        ),
    ]
