# Generated by Django 2.1.1 on 2018-10-12 03:41

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20181012_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(upload_to='picture/news'),
        ),
    ]
