# Generated by Django 2.1.1 on 2018-11-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
