# Generated by Django 2.1.1 on 2018-11-05 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20181106_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.Customer'),
        ),
    ]
