# Generated by Django 2.1.1 on 2018-11-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_auto_20181107_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('num', models.IntegerField()),
                ('course', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
