# Generated by Django 2.1.1 on 2018-10-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ManyToManyField(to='menu.Category'),
        ),
    ]
