# Generated by Django 2.1.1 on 2018-10-17 06:47

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='picture/menu'),
        ),
    ]
